global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Node Exporter - 시스템 하드웨어 메트릭
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
    scrape_interval: 10s
    metrics_path: /metrics
    honor_labels: true

  # Promtail - 로그 수집기 메트릭
  - job_name: "promtail"
    static_configs:
      - targets: ["localhost:9080"]
    scrape_interval: 15s

  # Prometheus 자체 메트릭
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 15s

  # RustDesk 서버 메트릭 (향후 확장용)
  - job_name: "rustdesk"
    static_configs:
      - targets: ["localhost:21117"]
    scrape_interval: 30s
    scrape_timeout: 10s
